"""
All the client's exceptions are in this module
"""

from sumarines_client import constants


class SubmarinesClientException(Exception):
    """
    The base submarine client exception
    """

    pass


class ProtocolException(SubmarinesClientException):
    """
    A generic protocol error
    """

    pass


class ErrorMessageException(SubmarinesClientException):
    """
    An error generated by an error message
    """

    def __init__(self, error_code: constants.ErrorCode, message: str):
        self.error_code = error_code
        super().__init__(f'An error message was received - {error_code.name}({error_code}):\n\t{message}')


class GenericException(ErrorMessageException):
    """
    A generic error message exception
    """

    def __init__(self, message: str = 'A generic error (no additional information)'):
        super().__init__(constants.ErrorCode.GENERIC_ERROR, message)


class AlreadyAttackedException(ErrorMessageException):
    """
    Raised when the given coordinate was already attacked
    """

    def __init__(self, message: str = 'The coordinate you chose was already attacked, turn is passed...'):
        super().__init__(constants.ErrorCode.ALREADY_ATTACKED_ERROR, message)


class InvalidCoordinateException(ErrorMessageException):
    """
    Raised when the given coordinate is out of bound
    """

    def __init__(self, message: str = 'The coordinate you chose is out of bounds, turn is passed...'):
        super().__init__(constants.ErrorCode.INVALID_COORDINATE_ERROR, message)
